### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by Nagatakidani** [Nagatakidani/chat-space#11]
#IPアドレス
3.112.133.98

**Comment by yasunamiura** [comment]
長瀧谷さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**文頭にMemebr:を追記しましょう**
<img width="1069" alt="ChatSpace" src="https://user-images.githubusercontent.com/52514431/76745064-91718200-67b8-11ea-8dce-9df114a282b0.png">
見本
<img width="1185" alt="ChatSpaceSample" src="https://user-images.githubusercontent.com/52514431/76745156-b8c84f00-67b8-11ea-8ce6-9743c68e0aab.png">


修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by Nagatakidani** [comment]
修正致しました

**Comment by naru6117** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
